/* GENERATED BY MAKEFILE */

#include <errno.h>
#include <fcntl.h>
#include <linux/prctl.h>
#include <linux/sched.h>
#include <stddef.h>
#include <signal.h>
#include <sys/stat.h>
#include <sys/types.h>

#include "arch.h"
#include "libconstants.h"

const struct constant_entry constant_table[] = {
#ifdef MINIJAIL_ARCH_NR
    {"MINIJAIL_ARCH_NR", (unsigned long)MINIJAIL_ARCH_NR},
#endif // MINIJAIL_ARCH_NR
#ifdef MINIJAIL_ARCH_BITS
    {"MINIJAIL_ARCH_BITS", (unsigned long)MINIJAIL_ARCH_BITS},
#endif // MINIJAIL_ARCH_BITS
#ifdef AT_EACCESS
    {"AT_EACCESS", (unsigned long)AT_EACCESS},
#endif  // AT_EACCESS
#ifdef AT_REMOVEDIR
    {"AT_REMOVEDIR", (unsigned long)AT_REMOVEDIR},
#endif  // AT_REMOVEDIR
#ifdef AT_SYMLINK_FOLLOW
    {"AT_SYMLINK_FOLLOW", (unsigned long)AT_SYMLINK_FOLLOW},
#endif  // AT_SYMLINK_FOLLOW
#ifdef AT_SYMLINK_NOFOLLOW
    {"AT_SYMLINK_NOFOLLOW", (unsigned long)AT_SYMLINK_NOFOLLOW},
#endif  // AT_SYMLINK_NOFOLLOW
#ifdef BUS_ADRALN
    {"BUS_ADRALN", (unsigned long)BUS_ADRALN},
#endif  // BUS_ADRALN
#ifdef BUS_ADRERR
    {"BUS_ADRERR", (unsigned long)BUS_ADRERR},
#endif  // BUS_ADRERR
#ifdef BUS_MCEERR_AO
    {"BUS_MCEERR_AO", (unsigned long)BUS_MCEERR_AO},
#endif  // BUS_MCEERR_AO
#ifdef BUS_MCEERR_AR
    {"BUS_MCEERR_AR", (unsigned long)BUS_MCEERR_AR},
#endif  // BUS_MCEERR_AR
#ifdef BUS_OBJERR
    {"BUS_OBJERR", (unsigned long)BUS_OBJERR},
#endif  // BUS_OBJERR
#ifdef CLD_CONTINUED
    {"CLD_CONTINUED", (unsigned long)CLD_CONTINUED},
#endif  // CLD_CONTINUED
#ifdef CLD_DUMPED
    {"CLD_DUMPED", (unsigned long)CLD_DUMPED},
#endif  // CLD_DUMPED
#ifdef CLD_EXITED
    {"CLD_EXITED", (unsigned long)CLD_EXITED},
#endif  // CLD_EXITED
#ifdef CLD_KILLED
    {"CLD_KILLED", (unsigned long)CLD_KILLED},
#endif  // CLD_KILLED
#ifdef CLD_STOPPED
    {"CLD_STOPPED", (unsigned long)CLD_STOPPED},
#endif  // CLD_STOPPED
#ifdef CLD_TRAPPED
    {"CLD_TRAPPED", (unsigned long)CLD_TRAPPED},
#endif  // CLD_TRAPPED
#ifdef CLONE_CHILD_CLEARTID
    {"CLONE_CHILD_CLEARTID", (unsigned long)CLONE_CHILD_CLEARTID},
#endif  // CLONE_CHILD_CLEARTID
#ifdef CLONE_CHILD_SETTID
    {"CLONE_CHILD_SETTID", (unsigned long)CLONE_CHILD_SETTID},
#endif  // CLONE_CHILD_SETTID
#ifdef CLONE_DETACHED
    {"CLONE_DETACHED", (unsigned long)CLONE_DETACHED},
#endif  // CLONE_DETACHED
#ifdef CLONE_FILES
    {"CLONE_FILES", (unsigned long)CLONE_FILES},
#endif  // CLONE_FILES
#ifdef CLONE_FS
    {"CLONE_FS", (unsigned long)CLONE_FS},
#endif  // CLONE_FS
#ifdef CLONE_IO
    {"CLONE_IO", (unsigned long)CLONE_IO},
#endif  // CLONE_IO
#ifdef CLONE_NEWIPC
    {"CLONE_NEWIPC", (unsigned long)CLONE_NEWIPC},
#endif  // CLONE_NEWIPC
#ifdef CLONE_NEWNET
    {"CLONE_NEWNET", (unsigned long)CLONE_NEWNET},
#endif  // CLONE_NEWNET
#ifdef CLONE_NEWNS
    {"CLONE_NEWNS", (unsigned long)CLONE_NEWNS},
#endif  // CLONE_NEWNS
#ifdef CLONE_NEWPID
    {"CLONE_NEWPID", (unsigned long)CLONE_NEWPID},
#endif  // CLONE_NEWPID
#ifdef CLONE_NEWUSER
    {"CLONE_NEWUSER", (unsigned long)CLONE_NEWUSER},
#endif  // CLONE_NEWUSER
#ifdef CLONE_NEWUTS
    {"CLONE_NEWUTS", (unsigned long)CLONE_NEWUTS},
#endif  // CLONE_NEWUTS
#ifdef CLONE_PARENT
    {"CLONE_PARENT", (unsigned long)CLONE_PARENT},
#endif  // CLONE_PARENT
#ifdef CLONE_PARENT_SETTID
    {"CLONE_PARENT_SETTID", (unsigned long)CLONE_PARENT_SETTID},
#endif  // CLONE_PARENT_SETTID
#ifdef CLONE_PTRACE
    {"CLONE_PTRACE", (unsigned long)CLONE_PTRACE},
#endif  // CLONE_PTRACE
#ifdef CLONE_SETTLS
    {"CLONE_SETTLS", (unsigned long)CLONE_SETTLS},
#endif  // CLONE_SETTLS
#ifdef CLONE_SIGHAND
    {"CLONE_SIGHAND", (unsigned long)CLONE_SIGHAND},
#endif  // CLONE_SIGHAND
#ifdef CLONE_SYSVSEM
    {"CLONE_SYSVSEM", (unsigned long)CLONE_SYSVSEM},
#endif  // CLONE_SYSVSEM
#ifdef CLONE_THREAD
    {"CLONE_THREAD", (unsigned long)CLONE_THREAD},
#endif  // CLONE_THREAD
#ifdef CLONE_UNTRACED
    {"CLONE_UNTRACED", (unsigned long)CLONE_UNTRACED},
#endif  // CLONE_UNTRACED
#ifdef CLONE_VFORK
    {"CLONE_VFORK", (unsigned long)CLONE_VFORK},
#endif  // CLONE_VFORK
#ifdef CLONE_VM
    {"CLONE_VM", (unsigned long)CLONE_VM},
#endif  // CLONE_VM
#ifdef CSIGNAL
    {"CSIGNAL", (unsigned long)CSIGNAL},
#endif  // CSIGNAL
#ifdef E2BIG
    {"E2BIG", (unsigned long)E2BIG},
#endif  // E2BIG
#ifdef EACCES
    {"EACCES", (unsigned long)EACCES},
#endif  // EACCES
#ifdef EADDRINUSE
    {"EADDRINUSE", (unsigned long)EADDRINUSE},
#endif  // EADDRINUSE
#ifdef EADDRNOTAVAIL
    {"EADDRNOTAVAIL", (unsigned long)EADDRNOTAVAIL},
#endif  // EADDRNOTAVAIL
#ifdef EADV
    {"EADV", (unsigned long)EADV},
#endif  // EADV
#ifdef EAFNOSUPPORT
    {"EAFNOSUPPORT", (unsigned long)EAFNOSUPPORT},
#endif  // EAFNOSUPPORT
#ifdef EAGAIN
    {"EAGAIN", (unsigned long)EAGAIN},
#endif  // EAGAIN
#ifdef EALREADY
    {"EALREADY", (unsigned long)EALREADY},
#endif  // EALREADY
#ifdef EBADE
    {"EBADE", (unsigned long)EBADE},
#endif  // EBADE
#ifdef EBADF
    {"EBADF", (unsigned long)EBADF},
#endif  // EBADF
#ifdef EBADFD
    {"EBADFD", (unsigned long)EBADFD},
#endif  // EBADFD
#ifdef EBADMSG
    {"EBADMSG", (unsigned long)EBADMSG},
#endif  // EBADMSG
#ifdef EBADR
    {"EBADR", (unsigned long)EBADR},
#endif  // EBADR
#ifdef EBADRQC
    {"EBADRQC", (unsigned long)EBADRQC},
#endif  // EBADRQC
#ifdef EBADSLT
    {"EBADSLT", (unsigned long)EBADSLT},
#endif  // EBADSLT
#ifdef EBFONT
    {"EBFONT", (unsigned long)EBFONT},
#endif  // EBFONT
#ifdef EBUSY
    {"EBUSY", (unsigned long)EBUSY},
#endif  // EBUSY
#ifdef ECANCELED
    {"ECANCELED", (unsigned long)ECANCELED},
#endif  // ECANCELED
#ifdef ECHILD
    {"ECHILD", (unsigned long)ECHILD},
#endif  // ECHILD
#ifdef ECHRNG
    {"ECHRNG", (unsigned long)ECHRNG},
#endif  // ECHRNG
#ifdef ECOMM
    {"ECOMM", (unsigned long)ECOMM},
#endif  // ECOMM
#ifdef ECONNABORTED
    {"ECONNABORTED", (unsigned long)ECONNABORTED},
#endif  // ECONNABORTED
#ifdef ECONNREFUSED
    {"ECONNREFUSED", (unsigned long)ECONNREFUSED},
#endif  // ECONNREFUSED
#ifdef ECONNRESET
    {"ECONNRESET", (unsigned long)ECONNRESET},
#endif  // ECONNRESET
#ifdef EDEADLK
    {"EDEADLK", (unsigned long)EDEADLK},
#endif  // EDEADLK
#ifdef EDEADLOCK
    {"EDEADLOCK", (unsigned long)EDEADLOCK},
#endif  // EDEADLOCK
#ifdef EDESTADDRREQ
    {"EDESTADDRREQ", (unsigned long)EDESTADDRREQ},
#endif  // EDESTADDRREQ
#ifdef EDOM
    {"EDOM", (unsigned long)EDOM},
#endif  // EDOM
#ifdef EDOTDOT
    {"EDOTDOT", (unsigned long)EDOTDOT},
#endif  // EDOTDOT
#ifdef EDQUOT
    {"EDQUOT", (unsigned long)EDQUOT},
#endif  // EDQUOT
#ifdef EEXIST
    {"EEXIST", (unsigned long)EEXIST},
#endif  // EEXIST
#ifdef EFAULT
    {"EFAULT", (unsigned long)EFAULT},
#endif  // EFAULT
#ifdef EFBIG
    {"EFBIG", (unsigned long)EFBIG},
#endif  // EFBIG
#ifdef EHOSTDOWN
    {"EHOSTDOWN", (unsigned long)EHOSTDOWN},
#endif  // EHOSTDOWN
#ifdef EHOSTUNREACH
    {"EHOSTUNREACH", (unsigned long)EHOSTUNREACH},
#endif  // EHOSTUNREACH
#ifdef EHWPOISON
    {"EHWPOISON", (unsigned long)EHWPOISON},
#endif  // EHWPOISON
#ifdef EIDRM
    {"EIDRM", (unsigned long)EIDRM},
#endif  // EIDRM
#ifdef EILSEQ
    {"EILSEQ", (unsigned long)EILSEQ},
#endif  // EILSEQ
#ifdef EINPROGRESS
    {"EINPROGRESS", (unsigned long)EINPROGRESS},
#endif  // EINPROGRESS
#ifdef EINTR
    {"EINTR", (unsigned long)EINTR},
#endif  // EINTR
#ifdef EINVAL
    {"EINVAL", (unsigned long)EINVAL},
#endif  // EINVAL
#ifdef EIO
    {"EIO", (unsigned long)EIO},
#endif  // EIO
#ifdef EISCONN
    {"EISCONN", (unsigned long)EISCONN},
#endif  // EISCONN
#ifdef EISDIR
    {"EISDIR", (unsigned long)EISDIR},
#endif  // EISDIR
#ifdef EISNAM
    {"EISNAM", (unsigned long)EISNAM},
#endif  // EISNAM
#ifdef EKEYEXPIRED
    {"EKEYEXPIRED", (unsigned long)EKEYEXPIRED},
#endif  // EKEYEXPIRED
#ifdef EKEYREJECTED
    {"EKEYREJECTED", (unsigned long)EKEYREJECTED},
#endif  // EKEYREJECTED
#ifdef EKEYREVOKED
    {"EKEYREVOKED", (unsigned long)EKEYREVOKED},
#endif  // EKEYREVOKED
#ifdef EL2HLT
    {"EL2HLT", (unsigned long)EL2HLT},
#endif  // EL2HLT
#ifdef EL2NSYNC
    {"EL2NSYNC", (unsigned long)EL2NSYNC},
#endif  // EL2NSYNC
#ifdef EL3HLT
    {"EL3HLT", (unsigned long)EL3HLT},
#endif  // EL3HLT
#ifdef EL3RST
    {"EL3RST", (unsigned long)EL3RST},
#endif  // EL3RST
#ifdef ELIBACC
    {"ELIBACC", (unsigned long)ELIBACC},
#endif  // ELIBACC
#ifdef ELIBBAD
    {"ELIBBAD", (unsigned long)ELIBBAD},
#endif  // ELIBBAD
#ifdef ELIBEXEC
    {"ELIBEXEC", (unsigned long)ELIBEXEC},
#endif  // ELIBEXEC
#ifdef ELIBMAX
    {"ELIBMAX", (unsigned long)ELIBMAX},
#endif  // ELIBMAX
#ifdef ELIBSCN
    {"ELIBSCN", (unsigned long)ELIBSCN},
#endif  // ELIBSCN
#ifdef ELNRNG
    {"ELNRNG", (unsigned long)ELNRNG},
#endif  // ELNRNG
#ifdef ELOOP
    {"ELOOP", (unsigned long)ELOOP},
#endif  // ELOOP
#ifdef EMEDIUMTYPE
    {"EMEDIUMTYPE", (unsigned long)EMEDIUMTYPE},
#endif  // EMEDIUMTYPE
#ifdef EMFILE
    {"EMFILE", (unsigned long)EMFILE},
#endif  // EMFILE
#ifdef EMLINK
    {"EMLINK", (unsigned long)EMLINK},
#endif  // EMLINK
#ifdef EMSGSIZE
    {"EMSGSIZE", (unsigned long)EMSGSIZE},
#endif  // EMSGSIZE
#ifdef EMULTIHOP
    {"EMULTIHOP", (unsigned long)EMULTIHOP},
#endif  // EMULTIHOP
#ifdef ENAMETOOLONG
    {"ENAMETOOLONG", (unsigned long)ENAMETOOLONG},
#endif  // ENAMETOOLONG
#ifdef ENAVAIL
    {"ENAVAIL", (unsigned long)ENAVAIL},
#endif  // ENAVAIL
#ifdef ENETDOWN
    {"ENETDOWN", (unsigned long)ENETDOWN},
#endif  // ENETDOWN
#ifdef ENETRESET
    {"ENETRESET", (unsigned long)ENETRESET},
#endif  // ENETRESET
#ifdef ENETUNREACH
    {"ENETUNREACH", (unsigned long)ENETUNREACH},
#endif  // ENETUNREACH
#ifdef ENFILE
    {"ENFILE", (unsigned long)ENFILE},
#endif  // ENFILE
#ifdef ENOANO
    {"ENOANO", (unsigned long)ENOANO},
#endif  // ENOANO
#ifdef ENOBUFS
    {"ENOBUFS", (unsigned long)ENOBUFS},
#endif  // ENOBUFS
#ifdef ENOCSI
    {"ENOCSI", (unsigned long)ENOCSI},
#endif  // ENOCSI
#ifdef ENODATA
    {"ENODATA", (unsigned long)ENODATA},
#endif  // ENODATA
#ifdef ENODEV
    {"ENODEV", (unsigned long)ENODEV},
#endif  // ENODEV
#ifdef ENOENT
    {"ENOENT", (unsigned long)ENOENT},
#endif  // ENOENT
#ifdef ENOEXEC
    {"ENOEXEC", (unsigned long)ENOEXEC},
#endif  // ENOEXEC
#ifdef ENOKEY
    {"ENOKEY", (unsigned long)ENOKEY},
#endif  // ENOKEY
#ifdef ENOLCK
    {"ENOLCK", (unsigned long)ENOLCK},
#endif  // ENOLCK
#ifdef ENOLINK
    {"ENOLINK", (unsigned long)ENOLINK},
#endif  // ENOLINK
#ifdef ENOMEDIUM
    {"ENOMEDIUM", (unsigned long)ENOMEDIUM},
#endif  // ENOMEDIUM
#ifdef ENOMEM
    {"ENOMEM", (unsigned long)ENOMEM},
#endif  // ENOMEM
#ifdef ENOMSG
    {"ENOMSG", (unsigned long)ENOMSG},
#endif  // ENOMSG
#ifdef ENONET
    {"ENONET", (unsigned long)ENONET},
#endif  // ENONET
#ifdef ENOPKG
    {"ENOPKG", (unsigned long)ENOPKG},
#endif  // ENOPKG
#ifdef ENOPROTOOPT
    {"ENOPROTOOPT", (unsigned long)ENOPROTOOPT},
#endif  // ENOPROTOOPT
#ifdef ENOSPC
    {"ENOSPC", (unsigned long)ENOSPC},
#endif  // ENOSPC
#ifdef ENOSR
    {"ENOSR", (unsigned long)ENOSR},
#endif  // ENOSR
#ifdef ENOSTR
    {"ENOSTR", (unsigned long)ENOSTR},
#endif  // ENOSTR
#ifdef ENOSYS
    {"ENOSYS", (unsigned long)ENOSYS},
#endif  // ENOSYS
#ifdef ENOTBLK
    {"ENOTBLK", (unsigned long)ENOTBLK},
#endif  // ENOTBLK
#ifdef ENOTCONN
    {"ENOTCONN", (unsigned long)ENOTCONN},
#endif  // ENOTCONN
#ifdef ENOTDIR
    {"ENOTDIR", (unsigned long)ENOTDIR},
#endif  // ENOTDIR
#ifdef ENOTEMPTY
    {"ENOTEMPTY", (unsigned long)ENOTEMPTY},
#endif  // ENOTEMPTY
#ifdef ENOTNAM
    {"ENOTNAM", (unsigned long)ENOTNAM},
#endif  // ENOTNAM
#ifdef ENOTRECOVERABLE
    {"ENOTRECOVERABLE", (unsigned long)ENOTRECOVERABLE},
#endif  // ENOTRECOVERABLE
#ifdef ENOTSOCK
    {"ENOTSOCK", (unsigned long)ENOTSOCK},
#endif  // ENOTSOCK
#ifdef ENOTSUP
    {"ENOTSUP", (unsigned long)ENOTSUP},
#endif  // ENOTSUP
#ifdef ENOTTY
    {"ENOTTY", (unsigned long)ENOTTY},
#endif  // ENOTTY
#ifdef ENOTUNIQ
    {"ENOTUNIQ", (unsigned long)ENOTUNIQ},
#endif  // ENOTUNIQ
#ifdef ENXIO
    {"ENXIO", (unsigned long)ENXIO},
#endif  // ENXIO
#ifdef EOPNOTSUPP
    {"EOPNOTSUPP", (unsigned long)EOPNOTSUPP},
#endif  // EOPNOTSUPP
#ifdef EOVERFLOW
    {"EOVERFLOW", (unsigned long)EOVERFLOW},
#endif  // EOVERFLOW
#ifdef EOWNERDEAD
    {"EOWNERDEAD", (unsigned long)EOWNERDEAD},
#endif  // EOWNERDEAD
#ifdef EPERM
    {"EPERM", (unsigned long)EPERM},
#endif  // EPERM
#ifdef EPFNOSUPPORT
    {"EPFNOSUPPORT", (unsigned long)EPFNOSUPPORT},
#endif  // EPFNOSUPPORT
#ifdef EPIPE
    {"EPIPE", (unsigned long)EPIPE},
#endif  // EPIPE
#ifdef EPROTO
    {"EPROTO", (unsigned long)EPROTO},
#endif  // EPROTO
#ifdef EPROTONOSUPPORT
    {"EPROTONOSUPPORT", (unsigned long)EPROTONOSUPPORT},
#endif  // EPROTONOSUPPORT
#ifdef EPROTOTYPE
    {"EPROTOTYPE", (unsigned long)EPROTOTYPE},
#endif  // EPROTOTYPE
#ifdef ERANGE
    {"ERANGE", (unsigned long)ERANGE},
#endif  // ERANGE
#ifdef EREMCHG
    {"EREMCHG", (unsigned long)EREMCHG},
#endif  // EREMCHG
#ifdef EREMOTE
    {"EREMOTE", (unsigned long)EREMOTE},
#endif  // EREMOTE
#ifdef EREMOTEIO
    {"EREMOTEIO", (unsigned long)EREMOTEIO},
#endif  // EREMOTEIO
#ifdef ERESTART
    {"ERESTART", (unsigned long)ERESTART},
#endif  // ERESTART
#ifdef ERFKILL
    {"ERFKILL", (unsigned long)ERFKILL},
#endif  // ERFKILL
#ifdef EROFS
    {"EROFS", (unsigned long)EROFS},
#endif  // EROFS
#ifdef ESHUTDOWN
    {"ESHUTDOWN", (unsigned long)ESHUTDOWN},
#endif  // ESHUTDOWN
#ifdef ESOCKTNOSUPPORT
    {"ESOCKTNOSUPPORT", (unsigned long)ESOCKTNOSUPPORT},
#endif  // ESOCKTNOSUPPORT
#ifdef ESPIPE
    {"ESPIPE", (unsigned long)ESPIPE},
#endif  // ESPIPE
#ifdef ESRCH
    {"ESRCH", (unsigned long)ESRCH},
#endif  // ESRCH
#ifdef ESRMNT
    {"ESRMNT", (unsigned long)ESRMNT},
#endif  // ESRMNT
#ifdef ESTALE
    {"ESTALE", (unsigned long)ESTALE},
#endif  // ESTALE
#ifdef ESTRPIPE
    {"ESTRPIPE", (unsigned long)ESTRPIPE},
#endif  // ESTRPIPE
#ifdef ETIME
    {"ETIME", (unsigned long)ETIME},
#endif  // ETIME
#ifdef ETIMEDOUT
    {"ETIMEDOUT", (unsigned long)ETIMEDOUT},
#endif  // ETIMEDOUT
#ifdef ETOOMANYREFS
    {"ETOOMANYREFS", (unsigned long)ETOOMANYREFS},
#endif  // ETOOMANYREFS
#ifdef ETXTBSY
    {"ETXTBSY", (unsigned long)ETXTBSY},
#endif  // ETXTBSY
#ifdef EUCLEAN
    {"EUCLEAN", (unsigned long)EUCLEAN},
#endif  // EUCLEAN
#ifdef EUNATCH
    {"EUNATCH", (unsigned long)EUNATCH},
#endif  // EUNATCH
#ifdef EUSERS
    {"EUSERS", (unsigned long)EUSERS},
#endif  // EUSERS
#ifdef EWOULDBLOCK
    {"EWOULDBLOCK", (unsigned long)EWOULDBLOCK},
#endif  // EWOULDBLOCK
#ifdef EXDEV
    {"EXDEV", (unsigned long)EXDEV},
#endif  // EXDEV
#ifdef EXFULL
    {"EXFULL", (unsigned long)EXFULL},
#endif  // EXFULL
#ifdef FAPPEND
    {"FAPPEND", (unsigned long)FAPPEND},
#endif  // FAPPEND
#ifdef FASYNC
    {"FASYNC", (unsigned long)FASYNC},
#endif  // FASYNC
#ifdef FD_CLOEXEC
    {"FD_CLOEXEC", (unsigned long)FD_CLOEXEC},
#endif  // FD_CLOEXEC
#ifdef F_DUPFD
    {"F_DUPFD", (unsigned long)F_DUPFD},
#endif  // F_DUPFD
#ifdef F_DUPFD_CLOEXEC
    {"F_DUPFD_CLOEXEC", (unsigned long)F_DUPFD_CLOEXEC},
#endif  // F_DUPFD_CLOEXEC
#ifdef F_EXLCK
    {"F_EXLCK", (unsigned long)F_EXLCK},
#endif  // F_EXLCK
#ifdef FFSYNC
    {"FFSYNC", (unsigned long)FFSYNC},
#endif  // FFSYNC
#ifdef F_GETFD
    {"F_GETFD", (unsigned long)F_GETFD},
#endif  // F_GETFD
#ifdef F_GETFL
    {"F_GETFL", (unsigned long)F_GETFL},
#endif  // F_GETFL
#ifdef F_GETLK
    {"F_GETLK", (unsigned long)F_GETLK},
#endif  // F_GETLK
#ifdef F_GETLK64
    {"F_GETLK64", (unsigned long)F_GETLK64},
#endif  // F_GETLK64
#ifdef F_LOCK
    {"F_LOCK", (unsigned long)F_LOCK},
#endif  // F_LOCK
#ifdef FNDELAY
    {"FNDELAY", (unsigned long)FNDELAY},
#endif  // FNDELAY
#ifdef FNONBLOCK
    {"FNONBLOCK", (unsigned long)FNONBLOCK},
#endif  // FNONBLOCK
#ifdef F_OK
    {"F_OK", (unsigned long)F_OK},
#endif  // F_OK
#ifdef FPE_FLTDIV
    {"FPE_FLTDIV", (unsigned long)FPE_FLTDIV},
#endif  // FPE_FLTDIV
#ifdef FPE_FLTINV
    {"FPE_FLTINV", (unsigned long)FPE_FLTINV},
#endif  // FPE_FLTINV
#ifdef FPE_FLTOVF
    {"FPE_FLTOVF", (unsigned long)FPE_FLTOVF},
#endif  // FPE_FLTOVF
#ifdef FPE_FLTRES
    {"FPE_FLTRES", (unsigned long)FPE_FLTRES},
#endif  // FPE_FLTRES
#ifdef FPE_FLTSUB
    {"FPE_FLTSUB", (unsigned long)FPE_FLTSUB},
#endif  // FPE_FLTSUB
#ifdef FPE_FLTUND
    {"FPE_FLTUND", (unsigned long)FPE_FLTUND},
#endif  // FPE_FLTUND
#ifdef FPE_INTDIV
    {"FPE_INTDIV", (unsigned long)FPE_INTDIV},
#endif  // FPE_INTDIV
#ifdef FPE_INTOVF
    {"FPE_INTOVF", (unsigned long)FPE_INTOVF},
#endif  // FPE_INTOVF
#ifdef FP_XSTATE_MAGIC1
    {"FP_XSTATE_MAGIC1", (unsigned long)FP_XSTATE_MAGIC1},
#endif  // FP_XSTATE_MAGIC1
#ifdef FP_XSTATE_MAGIC2
    {"FP_XSTATE_MAGIC2", (unsigned long)FP_XSTATE_MAGIC2},
#endif  // FP_XSTATE_MAGIC2
#ifdef FP_XSTATE_MAGIC2_SIZE
    {"FP_XSTATE_MAGIC2_SIZE", (unsigned long)FP_XSTATE_MAGIC2_SIZE},
#endif  // FP_XSTATE_MAGIC2_SIZE
#ifdef F_RDLCK
    {"F_RDLCK", (unsigned long)F_RDLCK},
#endif  // F_RDLCK
#ifdef F_SETFD
    {"F_SETFD", (unsigned long)F_SETFD},
#endif  // F_SETFD
#ifdef F_SETFL
    {"F_SETFL", (unsigned long)F_SETFL},
#endif  // F_SETFL
#ifdef F_SETLK
    {"F_SETLK", (unsigned long)F_SETLK},
#endif  // F_SETLK
#ifdef F_SETLK64
    {"F_SETLK64", (unsigned long)F_SETLK64},
#endif  // F_SETLK64
#ifdef F_SETLKW64
    {"F_SETLKW64", (unsigned long)F_SETLKW64},
#endif  // F_SETLKW64
#ifdef F_SETLKW
    {"F_SETLKW", (unsigned long)F_SETLKW},
#endif  // F_SETLKW
#ifdef F_SHLCK
    {"F_SHLCK", (unsigned long)F_SHLCK},
#endif  // F_SHLCK
#ifdef F_TEST
    {"F_TEST", (unsigned long)F_TEST},
#endif  // F_TEST
#ifdef F_TLOCK
    {"F_TLOCK", (unsigned long)F_TLOCK},
#endif  // F_TLOCK
#ifdef F_ULOCK
    {"F_ULOCK", (unsigned long)F_ULOCK},
#endif  // F_ULOCK
#ifdef F_UNLCK
    {"F_UNLCK", (unsigned long)F_UNLCK},
#endif  // F_UNLCK
#ifdef F_WRLCK
    {"F_WRLCK", (unsigned long)F_WRLCK},
#endif  // F_WRLCK
#ifdef ILL_BADSTK
    {"ILL_BADSTK", (unsigned long)ILL_BADSTK},
#endif  // ILL_BADSTK
#ifdef ILL_COPROC
    {"ILL_COPROC", (unsigned long)ILL_COPROC},
#endif  // ILL_COPROC
#ifdef ILL_ILLADR
    {"ILL_ILLADR", (unsigned long)ILL_ILLADR},
#endif  // ILL_ILLADR
#ifdef ILL_ILLOPC
    {"ILL_ILLOPC", (unsigned long)ILL_ILLOPC},
#endif  // ILL_ILLOPC
#ifdef ILL_ILLOPN
    {"ILL_ILLOPN", (unsigned long)ILL_ILLOPN},
#endif  // ILL_ILLOPN
#ifdef ILL_ILLTRP
    {"ILL_ILLTRP", (unsigned long)ILL_ILLTRP},
#endif  // ILL_ILLTRP
#ifdef ILL_PRVOPC
    {"ILL_PRVOPC", (unsigned long)ILL_PRVOPC},
#endif  // ILL_PRVOPC
#ifdef ILL_PRVREG
    {"ILL_PRVREG", (unsigned long)ILL_PRVREG},
#endif  // ILL_PRVREG
#ifdef LOCK_EX
    {"LOCK_EX", (unsigned long)LOCK_EX},
#endif  // LOCK_EX
#ifdef LOCK_NB
    {"LOCK_NB", (unsigned long)LOCK_NB},
#endif  // LOCK_NB
#ifdef LOCK_SH
    {"LOCK_SH", (unsigned long)LOCK_SH},
#endif  // LOCK_SH
#ifdef LOCK_UN
    {"LOCK_UN", (unsigned long)LOCK_UN},
#endif  // LOCK_UN
#ifdef MINSIGSTKSZ
    {"MINSIGSTKSZ", (unsigned long)MINSIGSTKSZ},
#endif  // MINSIGSTKSZ
#ifdef NGREG
    {"NGREG", (unsigned long)NGREG},
#endif  // NGREG
#ifdef O_ACCMODE
    {"O_ACCMODE", (unsigned long)O_ACCMODE},
#endif  // O_ACCMODE
#ifdef O_APPEND
    {"O_APPEND", (unsigned long)O_APPEND},
#endif  // O_APPEND
#ifdef O_ASYNC
    {"O_ASYNC", (unsigned long)O_ASYNC},
#endif  // O_ASYNC
#ifdef O_CREAT
    {"O_CREAT", (unsigned long)O_CREAT},
#endif  // O_CREAT
#ifdef O_EXCL
    {"O_EXCL", (unsigned long)O_EXCL},
#endif  // O_EXCL
#ifdef O_FSYNC
    {"O_FSYNC", (unsigned long)O_FSYNC},
#endif  // O_FSYNC
#ifdef O_NDELAY
    {"O_NDELAY", (unsigned long)O_NDELAY},
#endif  // O_NDELAY
#ifdef O_NOCTTY
    {"O_NOCTTY", (unsigned long)O_NOCTTY},
#endif  // O_NOCTTY
#ifdef O_NONBLOCK
    {"O_NONBLOCK", (unsigned long)O_NONBLOCK},
#endif  // O_NONBLOCK
#ifdef O_RDONLY
    {"O_RDONLY", (unsigned long)O_RDONLY},
#endif  // O_RDONLY
#ifdef O_RDWR
    {"O_RDWR", (unsigned long)O_RDWR},
#endif  // O_RDWR
#ifdef O_RSYNC
    {"O_RSYNC", (unsigned long)O_RSYNC},
#endif  // O_RSYNC
#ifdef O_SYNC
    {"O_SYNC", (unsigned long)O_SYNC},
#endif  // O_SYNC
#ifdef O_TRUNC
    {"O_TRUNC", (unsigned long)O_TRUNC},
#endif  // O_TRUNC
#ifdef O_WRONLY
    {"O_WRONLY", (unsigned long)O_WRONLY},
#endif  // O_WRONLY
#ifdef POLL_ERR
    {"POLL_ERR", (unsigned long)POLL_ERR},
#endif  // POLL_ERR
#ifdef POLL_HUP
    {"POLL_HUP", (unsigned long)POLL_HUP},
#endif  // POLL_HUP
#ifdef POLL_IN
    {"POLL_IN", (unsigned long)POLL_IN},
#endif  // POLL_IN
#ifdef POLL_MSG
    {"POLL_MSG", (unsigned long)POLL_MSG},
#endif  // POLL_MSG
#ifdef POLL_OUT
    {"POLL_OUT", (unsigned long)POLL_OUT},
#endif  // POLL_OUT
#ifdef POLL_PRI
    {"POLL_PRI", (unsigned long)POLL_PRI},
#endif  // POLL_PRI
#ifdef POSIX_FADV_NORMAL
    {"POSIX_FADV_NORMAL", (unsigned long)POSIX_FADV_NORMAL},
#endif  // POSIX_FADV_NORMAL
#ifdef POSIX_FADV_RANDOM
    {"POSIX_FADV_RANDOM", (unsigned long)POSIX_FADV_RANDOM},
#endif  // POSIX_FADV_RANDOM
#ifdef POSIX_FADV_SEQUENTIAL
    {"POSIX_FADV_SEQUENTIAL", (unsigned long)POSIX_FADV_SEQUENTIAL},
#endif  // POSIX_FADV_SEQUENTIAL
#ifdef POSIX_FADV_WILLNEED
    {"POSIX_FADV_WILLNEED", (unsigned long)POSIX_FADV_WILLNEED},
#endif  // POSIX_FADV_WILLNEED
#ifdef PR_CAPBSET_DROP
    {"PR_CAPBSET_DROP", (unsigned long)PR_CAPBSET_DROP},
#endif  // PR_CAPBSET_DROP
#ifdef PR_CAPBSET_READ
    {"PR_CAPBSET_READ", (unsigned long)PR_CAPBSET_READ},
#endif  // PR_CAPBSET_READ
#ifdef PR_ENDIAN_BIG
    {"PR_ENDIAN_BIG", (unsigned long)PR_ENDIAN_BIG},
#endif  // PR_ENDIAN_BIG
#ifdef PR_ENDIAN_LITTLE
    {"PR_ENDIAN_LITTLE", (unsigned long)PR_ENDIAN_LITTLE},
#endif  // PR_ENDIAN_LITTLE
#ifdef PR_ENDIAN_PPC_LITTLE
    {"PR_ENDIAN_PPC_LITTLE", (unsigned long)PR_ENDIAN_PPC_LITTLE},
#endif  // PR_ENDIAN_PPC_LITTLE
#ifdef PR_FPEMU_NOPRINT
    {"PR_FPEMU_NOPRINT", (unsigned long)PR_FPEMU_NOPRINT},
#endif  // PR_FPEMU_NOPRINT
#ifdef PR_FPEMU_SIGFPE
    {"PR_FPEMU_SIGFPE", (unsigned long)PR_FPEMU_SIGFPE},
#endif  // PR_FPEMU_SIGFPE
#ifdef PR_FP_EXC_ASYNC
    {"PR_FP_EXC_ASYNC", (unsigned long)PR_FP_EXC_ASYNC},
#endif  // PR_FP_EXC_ASYNC
#ifdef PR_FP_EXC_DISABLED
    {"PR_FP_EXC_DISABLED", (unsigned long)PR_FP_EXC_DISABLED},
#endif  // PR_FP_EXC_DISABLED
#ifdef PR_FP_EXC_DIV
    {"PR_FP_EXC_DIV", (unsigned long)PR_FP_EXC_DIV},
#endif  // PR_FP_EXC_DIV
#ifdef PR_FP_EXC_INV
    {"PR_FP_EXC_INV", (unsigned long)PR_FP_EXC_INV},
#endif  // PR_FP_EXC_INV
#ifdef PR_FP_EXC_NONRECOV
    {"PR_FP_EXC_NONRECOV", (unsigned long)PR_FP_EXC_NONRECOV},
#endif  // PR_FP_EXC_NONRECOV
#ifdef PR_FP_EXC_OVF
    {"PR_FP_EXC_OVF", (unsigned long)PR_FP_EXC_OVF},
#endif  // PR_FP_EXC_OVF
#ifdef PR_FP_EXC_PRECISE
    {"PR_FP_EXC_PRECISE", (unsigned long)PR_FP_EXC_PRECISE},
#endif  // PR_FP_EXC_PRECISE
#ifdef PR_FP_EXC_RES
    {"PR_FP_EXC_RES", (unsigned long)PR_FP_EXC_RES},
#endif  // PR_FP_EXC_RES
#ifdef PR_FP_EXC_SW_ENABLE
    {"PR_FP_EXC_SW_ENABLE", (unsigned long)PR_FP_EXC_SW_ENABLE},
#endif  // PR_FP_EXC_SW_ENABLE
#ifdef PR_FP_EXC_UND
    {"PR_FP_EXC_UND", (unsigned long)PR_FP_EXC_UND},
#endif  // PR_FP_EXC_UND
#ifdef PR_GET_CHILD_SUBREAPER
    {"PR_GET_CHILD_SUBREAPER", (unsigned long)PR_GET_CHILD_SUBREAPER},
#endif  // PR_GET_CHILD_SUBREAPER
#ifdef PR_GET_DUMPABLE
    {"PR_GET_DUMPABLE", (unsigned long)PR_GET_DUMPABLE},
#endif  // PR_GET_DUMPABLE
#ifdef PR_GET_ENDIAN
    {"PR_GET_ENDIAN", (unsigned long)PR_GET_ENDIAN},
#endif  // PR_GET_ENDIAN
#ifdef PR_GET_FPEMU
    {"PR_GET_FPEMU", (unsigned long)PR_GET_FPEMU},
#endif  // PR_GET_FPEMU
#ifdef PR_GET_FPEXC
    {"PR_GET_FPEXC", (unsigned long)PR_GET_FPEXC},
#endif  // PR_GET_FPEXC
#ifdef PR_GET_KEEPCAPS
    {"PR_GET_KEEPCAPS", (unsigned long)PR_GET_KEEPCAPS},
#endif  // PR_GET_KEEPCAPS
#ifdef PR_GET_NAME
    {"PR_GET_NAME", (unsigned long)PR_GET_NAME},
#endif  // PR_GET_NAME
#ifdef PR_GET_NO_NEW_PRIVS
    {"PR_GET_NO_NEW_PRIVS", (unsigned long)PR_GET_NO_NEW_PRIVS},
#endif  // PR_GET_NO_NEW_PRIVS
#ifdef PR_GET_PDEATHSIG
    {"PR_GET_PDEATHSIG", (unsigned long)PR_GET_PDEATHSIG},
#endif  // PR_GET_PDEATHSIG
#ifdef PR_GET_SECCOMP
    {"PR_GET_SECCOMP", (unsigned long)PR_GET_SECCOMP},
#endif  // PR_GET_SECCOMP
#ifdef PR_GET_SECUREBITS
    {"PR_GET_SECUREBITS", (unsigned long)PR_GET_SECUREBITS},
#endif  // PR_GET_SECUREBITS
#ifdef PR_GET_TID_ADDRESS
    {"PR_GET_TID_ADDRESS", (unsigned long)PR_GET_TID_ADDRESS},
#endif  // PR_GET_TID_ADDRESS
#ifdef PR_GET_TIMERSLACK
    {"PR_GET_TIMERSLACK", (unsigned long)PR_GET_TIMERSLACK},
#endif  // PR_GET_TIMERSLACK
#ifdef PR_GET_TIMING
    {"PR_GET_TIMING", (unsigned long)PR_GET_TIMING},
#endif  // PR_GET_TIMING
#ifdef PR_GET_TSC
    {"PR_GET_TSC", (unsigned long)PR_GET_TSC},
#endif  // PR_GET_TSC
#ifdef PR_GET_UNALIGN
    {"PR_GET_UNALIGN", (unsigned long)PR_GET_UNALIGN},
#endif  // PR_GET_UNALIGN
#ifdef PR_MCE_KILL
    {"PR_MCE_KILL", (unsigned long)PR_MCE_KILL},
#endif  // PR_MCE_KILL
#ifdef PR_MCE_KILL_CLEAR
    {"PR_MCE_KILL_CLEAR", (unsigned long)PR_MCE_KILL_CLEAR},
#endif  // PR_MCE_KILL_CLEAR
#ifdef PR_MCE_KILL_DEFAULT
    {"PR_MCE_KILL_DEFAULT", (unsigned long)PR_MCE_KILL_DEFAULT},
#endif  // PR_MCE_KILL_DEFAULT
#ifdef PR_MCE_KILL_EARLY
    {"PR_MCE_KILL_EARLY", (unsigned long)PR_MCE_KILL_EARLY},
#endif  // PR_MCE_KILL_EARLY
#ifdef PR_MCE_KILL_GET
    {"PR_MCE_KILL_GET", (unsigned long)PR_MCE_KILL_GET},
#endif  // PR_MCE_KILL_GET
#ifdef PR_MCE_KILL_LATE
    {"PR_MCE_KILL_LATE", (unsigned long)PR_MCE_KILL_LATE},
#endif  // PR_MCE_KILL_LATE
#ifdef PR_MCE_KILL_SET
    {"PR_MCE_KILL_SET", (unsigned long)PR_MCE_KILL_SET},
#endif  // PR_MCE_KILL_SET
#ifdef PR_SET_CHILD_SUBREAPER
    {"PR_SET_CHILD_SUBREAPER", (unsigned long)PR_SET_CHILD_SUBREAPER},
#endif  // PR_SET_CHILD_SUBREAPER
#ifdef PR_SET_DUMPABLE
    {"PR_SET_DUMPABLE", (unsigned long)PR_SET_DUMPABLE},
#endif  // PR_SET_DUMPABLE
#ifdef PR_SET_ENDIAN
    {"PR_SET_ENDIAN", (unsigned long)PR_SET_ENDIAN},
#endif  // PR_SET_ENDIAN
#ifdef PR_SET_FPEMU
    {"PR_SET_FPEMU", (unsigned long)PR_SET_FPEMU},
#endif  // PR_SET_FPEMU
#ifdef PR_SET_FPEXC
    {"PR_SET_FPEXC", (unsigned long)PR_SET_FPEXC},
#endif  // PR_SET_FPEXC
#ifdef PR_SET_KEEPCAPS
    {"PR_SET_KEEPCAPS", (unsigned long)PR_SET_KEEPCAPS},
#endif  // PR_SET_KEEPCAPS
#ifdef PR_SET_MM
    {"PR_SET_MM", (unsigned long)PR_SET_MM},
#endif  // PR_SET_MM
#ifdef PR_SET_MM_ARG_END
    {"PR_SET_MM_ARG_END", (unsigned long)PR_SET_MM_ARG_END},
#endif  // PR_SET_MM_ARG_END
#ifdef PR_SET_MM_ARG_START
    {"PR_SET_MM_ARG_START", (unsigned long)PR_SET_MM_ARG_START},
#endif  // PR_SET_MM_ARG_START
#ifdef PR_SET_MM_AUXV
    {"PR_SET_MM_AUXV", (unsigned long)PR_SET_MM_AUXV},
#endif  // PR_SET_MM_AUXV
#ifdef PR_SET_MM_BRK
    {"PR_SET_MM_BRK", (unsigned long)PR_SET_MM_BRK},
#endif  // PR_SET_MM_BRK
#ifdef PR_SET_MM_END_CODE
    {"PR_SET_MM_END_CODE", (unsigned long)PR_SET_MM_END_CODE},
#endif  // PR_SET_MM_END_CODE
#ifdef PR_SET_MM_END_DATA
    {"PR_SET_MM_END_DATA", (unsigned long)PR_SET_MM_END_DATA},
#endif  // PR_SET_MM_END_DATA
#ifdef PR_SET_MM_ENV_END
    {"PR_SET_MM_ENV_END", (unsigned long)PR_SET_MM_ENV_END},
#endif  // PR_SET_MM_ENV_END
#ifdef PR_SET_MM_ENV_START
    {"PR_SET_MM_ENV_START", (unsigned long)PR_SET_MM_ENV_START},
#endif  // PR_SET_MM_ENV_START
#ifdef PR_SET_MM_EXE_FILE
    {"PR_SET_MM_EXE_FILE", (unsigned long)PR_SET_MM_EXE_FILE},
#endif  // PR_SET_MM_EXE_FILE
#ifdef PR_SET_MM_START_BRK
    {"PR_SET_MM_START_BRK", (unsigned long)PR_SET_MM_START_BRK},
#endif  // PR_SET_MM_START_BRK
#ifdef PR_SET_MM_START_CODE
    {"PR_SET_MM_START_CODE", (unsigned long)PR_SET_MM_START_CODE},
#endif  // PR_SET_MM_START_CODE
#ifdef PR_SET_MM_START_DATA
    {"PR_SET_MM_START_DATA", (unsigned long)PR_SET_MM_START_DATA},
#endif  // PR_SET_MM_START_DATA
#ifdef PR_SET_MM_START_STACK
    {"PR_SET_MM_START_STACK", (unsigned long)PR_SET_MM_START_STACK},
#endif  // PR_SET_MM_START_STACK
#ifdef PR_SET_NAME
    {"PR_SET_NAME", (unsigned long)PR_SET_NAME},
#endif  // PR_SET_NAME
#ifdef PR_SET_NO_NEW_PRIVS
    {"PR_SET_NO_NEW_PRIVS", (unsigned long)PR_SET_NO_NEW_PRIVS},
#endif  // PR_SET_NO_NEW_PRIVS
#ifdef PR_SET_PDEATHSIG
    {"PR_SET_PDEATHSIG", (unsigned long)PR_SET_PDEATHSIG},
#endif  // PR_SET_PDEATHSIG
#ifdef PR_SET_PTRACER
    {"PR_SET_PTRACER", (unsigned long)PR_SET_PTRACER},
#endif  // PR_SET_PTRACER
#ifdef PR_SET_SECCOMP
    {"PR_SET_SECCOMP", (unsigned long)PR_SET_SECCOMP},
#endif  // PR_SET_SECCOMP
#ifdef PR_SET_SECUREBITS
    {"PR_SET_SECUREBITS", (unsigned long)PR_SET_SECUREBITS},
#endif  // PR_SET_SECUREBITS
#ifdef PR_SET_TIMERSLACK
    {"PR_SET_TIMERSLACK", (unsigned long)PR_SET_TIMERSLACK},
#endif  // PR_SET_TIMERSLACK
#ifdef PR_SET_TIMING
    {"PR_SET_TIMING", (unsigned long)PR_SET_TIMING},
#endif  // PR_SET_TIMING
#ifdef PR_SET_TSC
    {"PR_SET_TSC", (unsigned long)PR_SET_TSC},
#endif  // PR_SET_TSC
#ifdef PR_SET_UNALIGN
    {"PR_SET_UNALIGN", (unsigned long)PR_SET_UNALIGN},
#endif  // PR_SET_UNALIGN
#ifdef PR_TASK_PERF_EVENTS_DISABLE
    {"PR_TASK_PERF_EVENTS_DISABLE", (unsigned long)PR_TASK_PERF_EVENTS_DISABLE},
#endif  // PR_TASK_PERF_EVENTS_DISABLE
#ifdef PR_TASK_PERF_EVENTS_ENABLE
    {"PR_TASK_PERF_EVENTS_ENABLE", (unsigned long)PR_TASK_PERF_EVENTS_ENABLE},
#endif  // PR_TASK_PERF_EVENTS_ENABLE
#ifdef PR_TIMING_STATISTICAL
    {"PR_TIMING_STATISTICAL", (unsigned long)PR_TIMING_STATISTICAL},
#endif  // PR_TIMING_STATISTICAL
#ifdef PR_TIMING_TIMESTAMP
    {"PR_TIMING_TIMESTAMP", (unsigned long)PR_TIMING_TIMESTAMP},
#endif  // PR_TIMING_TIMESTAMP
#ifdef PR_TSC_ENABLE
    {"PR_TSC_ENABLE", (unsigned long)PR_TSC_ENABLE},
#endif  // PR_TSC_ENABLE
#ifdef PR_TSC_SIGSEGV
    {"PR_TSC_SIGSEGV", (unsigned long)PR_TSC_SIGSEGV},
#endif  // PR_TSC_SIGSEGV
#ifdef PR_UNALIGN_NOPRINT
    {"PR_UNALIGN_NOPRINT", (unsigned long)PR_UNALIGN_NOPRINT},
#endif  // PR_UNALIGN_NOPRINT
#ifdef PR_UNALIGN_SIGBUS
    {"PR_UNALIGN_SIGBUS", (unsigned long)PR_UNALIGN_SIGBUS},
#endif  // PR_UNALIGN_SIGBUS
#ifdef R_OK
    {"R_OK", (unsigned long)R_OK},
#endif  // R_OK
#ifdef SA_INTERRUPT
    {"SA_INTERRUPT", (unsigned long)SA_INTERRUPT},
#endif  // SA_INTERRUPT
#ifdef SA_NOCLDSTOP
    {"SA_NOCLDSTOP", (unsigned long)SA_NOCLDSTOP},
#endif  // SA_NOCLDSTOP
#ifdef SA_NOCLDWAIT
    {"SA_NOCLDWAIT", (unsigned long)SA_NOCLDWAIT},
#endif  // SA_NOCLDWAIT
#ifdef SA_NODEFER
    {"SA_NODEFER", (unsigned long)SA_NODEFER},
#endif  // SA_NODEFER
#ifdef SA_NOMASK
    {"SA_NOMASK", (unsigned long)SA_NOMASK},
#endif  // SA_NOMASK
#ifdef SA_ONESHOT
    {"SA_ONESHOT", (unsigned long)SA_ONESHOT},
#endif  // SA_ONESHOT
#ifdef SA_ONSTACK
    {"SA_ONSTACK", (unsigned long)SA_ONSTACK},
#endif  // SA_ONSTACK
#ifdef SA_RESETHAND
    {"SA_RESETHAND", (unsigned long)SA_RESETHAND},
#endif  // SA_RESETHAND
#ifdef SA_RESTART
    {"SA_RESTART", (unsigned long)SA_RESTART},
#endif  // SA_RESTART
#ifdef SA_SIGINFO
    {"SA_SIGINFO", (unsigned long)SA_SIGINFO},
#endif  // SA_SIGINFO
#ifdef SA_STACK
    {"SA_STACK", (unsigned long)SA_STACK},
#endif  // SA_STACK
#ifdef S_BLKSIZE
    {"S_BLKSIZE", (unsigned long)S_BLKSIZE},
#endif  // S_BLKSIZE
#ifdef SCHED_BATCH
    {"SCHED_BATCH", (unsigned long)SCHED_BATCH},
#endif  // SCHED_BATCH
#ifdef SCHED_FIFO
    {"SCHED_FIFO", (unsigned long)SCHED_FIFO},
#endif  // SCHED_FIFO
#ifdef SCHED_IDLE
    {"SCHED_IDLE", (unsigned long)SCHED_IDLE},
#endif  // SCHED_IDLE
#ifdef SCHED_NORMAL
    {"SCHED_NORMAL", (unsigned long)SCHED_NORMAL},
#endif  // SCHED_NORMAL
#ifdef SCHED_RESET_ON_FORK
    {"SCHED_RESET_ON_FORK", (unsigned long)SCHED_RESET_ON_FORK},
#endif  // SCHED_RESET_ON_FORK
#ifdef SCHED_RR
    {"SCHED_RR", (unsigned long)SCHED_RR},
#endif  // SCHED_RR
#ifdef SEEK_CUR
    {"SEEK_CUR", (unsigned long)SEEK_CUR},
#endif  // SEEK_CUR
#ifdef SEEK_END
    {"SEEK_END", (unsigned long)SEEK_END},
#endif  // SEEK_END
#ifdef SEEK_SET
    {"SEEK_SET", (unsigned long)SEEK_SET},
#endif  // SEEK_SET
#ifdef SEGV_ACCERR
    {"SEGV_ACCERR", (unsigned long)SEGV_ACCERR},
#endif  // SEGV_ACCERR
#ifdef SEGV_MAPERR
    {"SEGV_MAPERR", (unsigned long)SEGV_MAPERR},
#endif  // SEGV_MAPERR
#ifdef SI_ASYNCIO
    {"SI_ASYNCIO", (unsigned long)SI_ASYNCIO},
#endif  // SI_ASYNCIO
#ifdef SI_ASYNCNL
    {"SI_ASYNCNL", (unsigned long)SI_ASYNCNL},
#endif  // SI_ASYNCNL
#ifdef S_IEXEC
    {"S_IEXEC", (unsigned long)S_IEXEC},
#endif  // S_IEXEC
#ifdef SIGABRT
    {"SIGABRT", (unsigned long)SIGABRT},
#endif  // SIGABRT
#ifdef SIGALRM
    {"SIGALRM", (unsigned long)SIGALRM},
#endif  // SIGALRM
#ifdef SIGBUS
    {"SIGBUS", (unsigned long)SIGBUS},
#endif  // SIGBUS
#ifdef SIGCHLD
    {"SIGCHLD", (unsigned long)SIGCHLD},
#endif  // SIGCHLD
#ifdef SIGCLD
    {"SIGCLD", (unsigned long)SIGCLD},
#endif  // SIGCLD
#ifdef SIGCONT
    {"SIGCONT", (unsigned long)SIGCONT},
#endif  // SIGCONT
#ifdef SIGEV_NONE
    {"SIGEV_NONE", (unsigned long)SIGEV_NONE},
#endif  // SIGEV_NONE
#ifdef SIGEV_SIGNAL
    {"SIGEV_SIGNAL", (unsigned long)SIGEV_SIGNAL},
#endif  // SIGEV_SIGNAL
#ifdef SIGEV_THREAD_ID
    {"SIGEV_THREAD_ID", (unsigned long)SIGEV_THREAD_ID},
#endif  // SIGEV_THREAD_ID
#ifdef SIGEV_THREAD
    {"SIGEV_THREAD", (unsigned long)SIGEV_THREAD},
#endif  // SIGEV_THREAD
#ifdef SIGFPE
    {"SIGFPE", (unsigned long)SIGFPE},
#endif  // SIGFPE
#ifdef SIGHUP
    {"SIGHUP", (unsigned long)SIGHUP},
#endif  // SIGHUP
#ifdef SIGILL
    {"SIGILL", (unsigned long)SIGILL},
#endif  // SIGILL
#ifdef SIGINT
    {"SIGINT", (unsigned long)SIGINT},
#endif  // SIGINT
#ifdef SIGIO
    {"SIGIO", (unsigned long)SIGIO},
#endif  // SIGIO
#ifdef SIGIOT
    {"SIGIOT", (unsigned long)SIGIOT},
#endif  // SIGIOT
#ifdef SIGKILL
    {"SIGKILL", (unsigned long)SIGKILL},
#endif  // SIGKILL
#ifdef SIGPIPE
    {"SIGPIPE", (unsigned long)SIGPIPE},
#endif  // SIGPIPE
#ifdef SIGPOLL
    {"SIGPOLL", (unsigned long)SIGPOLL},
#endif  // SIGPOLL
#ifdef SIGPROF
    {"SIGPROF", (unsigned long)SIGPROF},
#endif  // SIGPROF
#ifdef SIGPWR
    {"SIGPWR", (unsigned long)SIGPWR},
#endif  // SIGPWR
#ifdef SIGQUIT
    {"SIGQUIT", (unsigned long)SIGQUIT},
#endif  // SIGQUIT
#ifdef SIGSEGV
    {"SIGSEGV", (unsigned long)SIGSEGV},
#endif  // SIGSEGV
#ifdef SIGSTKFLT
    {"SIGSTKFLT", (unsigned long)SIGSTKFLT},
#endif  // SIGSTKFLT
#ifdef SIGSTKSZ
    {"SIGSTKSZ", (unsigned long)SIGSTKSZ},
#endif  // SIGSTKSZ
#ifdef SIGSTOP
    {"SIGSTOP", (unsigned long)SIGSTOP},
#endif  // SIGSTOP
#ifdef SIGSYS
    {"SIGSYS", (unsigned long)SIGSYS},
#endif  // SIGSYS
#ifdef SIGTERM
    {"SIGTERM", (unsigned long)SIGTERM},
#endif  // SIGTERM
#ifdef SIGTRAP
    {"SIGTRAP", (unsigned long)SIGTRAP},
#endif  // SIGTRAP
#ifdef SIGTSTP
    {"SIGTSTP", (unsigned long)SIGTSTP},
#endif  // SIGTSTP
#ifdef SIGTTIN
    {"SIGTTIN", (unsigned long)SIGTTIN},
#endif  // SIGTTIN
#ifdef SIGTTOU
    {"SIGTTOU", (unsigned long)SIGTTOU},
#endif  // SIGTTOU
#ifdef SIGUNUSED
    {"SIGUNUSED", (unsigned long)SIGUNUSED},
#endif  // SIGUNUSED
#ifdef SIGURG
    {"SIGURG", (unsigned long)SIGURG},
#endif  // SIGURG
#ifdef SIGUSR1
    {"SIGUSR1", (unsigned long)SIGUSR1},
#endif  // SIGUSR1
#ifdef SIGUSR2
    {"SIGUSR2", (unsigned long)SIGUSR2},
#endif  // SIGUSR2
#ifdef SIGVTALRM
    {"SIGVTALRM", (unsigned long)SIGVTALRM},
#endif  // SIGVTALRM
#ifdef SIGWINCH
    {"SIGWINCH", (unsigned long)SIGWINCH},
#endif  // SIGWINCH
#ifdef SIGXCPU
    {"SIGXCPU", (unsigned long)SIGXCPU},
#endif  // SIGXCPU
#ifdef SIGXFSZ
    {"SIGXFSZ", (unsigned long)SIGXFSZ},
#endif  // SIGXFSZ
#ifdef SI_KERNEL
    {"SI_KERNEL", (unsigned long)SI_KERNEL},
#endif  // SI_KERNEL
#ifdef SI_MESGQ
    {"SI_MESGQ", (unsigned long)SI_MESGQ},
#endif  // SI_MESGQ
#ifdef SI_QUEUE
    {"SI_QUEUE", (unsigned long)SI_QUEUE},
#endif  // SI_QUEUE
#ifdef S_IREAD
    {"S_IREAD", (unsigned long)S_IREAD},
#endif  // S_IREAD
#ifdef SI_SIGIO
    {"SI_SIGIO", (unsigned long)SI_SIGIO},
#endif  // SI_SIGIO
#ifdef SI_TIMER
    {"SI_TIMER", (unsigned long)SI_TIMER},
#endif  // SI_TIMER
#ifdef SI_TKILL
    {"SI_TKILL", (unsigned long)SI_TKILL},
#endif  // SI_TKILL
#ifdef SI_USER
    {"SI_USER", (unsigned long)SI_USER},
#endif  // SI_USER
#ifdef S_IWRITE
    {"S_IWRITE", (unsigned long)S_IWRITE},
#endif  // S_IWRITE
#ifdef SS_DISABLE
    {"SS_DISABLE", (unsigned long)SS_DISABLE},
#endif  // SS_DISABLE
#ifdef SS_ONSTACK
    {"SS_ONSTACK", (unsigned long)SS_ONSTACK},
#endif  // SS_ONSTACK
#ifdef TRAP_BRKPT
    {"TRAP_BRKPT", (unsigned long)TRAP_BRKPT},
#endif  // TRAP_BRKPT
#ifdef TRAP_TRACE
    {"TRAP_TRACE", (unsigned long)TRAP_TRACE},
#endif  // TRAP_TRACE
#ifdef W_OK
    {"W_OK", (unsigned long)W_OK},
#endif  // W_OK
#ifdef X_OK
    {"X_OK", (unsigned long)X_OK},
#endif  // X_OK
    {NULL, 0},
};
