# GitHub actions workflow.
# https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions

# https://scan.coverity.com/projects/google-minijail
name: Coverity Scan

on:
  push:
    branches: [master]

  schedule:
    # The GH mirroring from Google GoB does not trigger push actions.
    # Fire it once a week to provide some coverage.
    - cron: '39 2 * * WED'

  # Allow for manual triggers from the web.
  workflow_dispatch:

jobs:
  coverity:
    strategy:
      matrix:
        os: [ubuntu-latest]
        cc: [clang]
    runs-on: ${{ matrix.os }}
    env:
      CC: ${{ matrix.cc }}
    steps:
    - uses: actions/checkout@v2
    - name: Install system packages
      run: sudo apt-get install -y libcap-dev
    - uses: vapier/coverity-scan-action@v1
      with:
        email: ${{ secrets.COVERITY_SCAN_EMAIL }}
        token: ${{ secrets.COVERITY_SCAN_TOKEN }}
